version: '3.2'

networks:
  proxy_network:
    external: true
volumes:
  db-data:
  zabbix-data:

services:
  web:
    image: nginx:latest
    container_name: web
    restart: always
    networks:
      - default
      - proxy_network
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ../WEB(FE)/build:/usr/share/nginx/html

  server:
    build:
      context: ../WEB(BE)
      dockerfile: Dockerfile
    container_name: server
    restart: always
    volumes:
      - "../WEB(BE):/app"
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=watchcon
      - DB_NAME=watchcon
      - DB_PORT=3306
    stdin_open: true
    tty: true

    # Release options
    # ports:
    #   - 80:8080

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=watchconroot
      - MYSQL_DATABASE=watchcon_db
      - MYSQL_USER=watchon_user
      - MYSQL_PASSWORD=watchon_password

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=watchconroot
      - PMA_ARBITRARY=1
    restart: always
    volumes:
      - /sessions
    networks:
      - default
      - proxy_network
    links:
      - mysql
    # Release options
    # ports:
    #   - 8080:80

  # Zabbix Settings
  zabbix_mysql:
    container_name: "zabbix_mysql"
    restart: "always"
    networks:
      - default
      - proxy_network
    image: mariadb
    # ports:
    #   - "3306:3306"
    volumes:
      - zabbix-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123"
      MYSQL_DATABASE: "zabbix"

  zabbix_server:
    container_name: "zabbix_server"
    restart: "always"
    image: zabbix/zabbix-server-mysql
    networks:
      - default
      - proxy_network
    # ports:
    #   - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/zabbix:/usr/lib/zabbix
    depends_on:
      - zabbix_mysql
    links:
      - zabbix_mysql:mysql
    environment:
      DB_SERVER_HOST: "mysql"
      MYSQL_USER: "zabbix"
      MYSQL_DATABASE: "zabbix"
      MYSQL_PASSWORD: "123"

  zabbix_nginx_web:
    container_name: "zabbix_nginx_web"
    restart: "always"
    image: zabbix/zabbix-web-nginx-mysql
    networks:
      - default
      - proxy_network
    # ports:
    #   - "8443:443"
    #   - "80:80"
    depends_on:
      - zabbix_mysql
      - zabbix_server
    links:
      - zabbix_mysql:mysql
      - zabbix_server:zabbix_server
    environment:
      DB_SERVER_HOST: "mysql"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123"
      MYSQL_DATABASE: "zabbix"
      ZBX_SERVER_HOST: "zabbix_server"
      PHP_TZ: "Asia/Seoul"
          
  zabbix-agent-a:
    image: zabbix/zabbix-agent
    networks:
      - default
      - proxy_network
    links: 
      - zabbix_server:zabbix_server
    container_name: zabbix-agent-a
    restart: always
    depends_on:
      - zabbix_server
    environment:
      - ZBX_HOSTNAME=zabbix-agent-a  
      - ZBX_SERVER_HOST=zabbix_server